####################CIUDAD##############
##
GET http://localhost:9000/properties/ciudad HTTP/1.1



####################PICTURES############################
###
GET http://localhost:9000/picture HTTP/1.1

###
POST http://localhost:9000/picture HTTP/1.1
Content-Type: application/json

{
    "img_url": "http://mariusn.com/themes/reales/images/prop/1-1.png",
    "img_datetime" : "26-10-2021",
    "img_principal":"0",
    "img_enable":"1",
    "id_prop":18
   
}
###
GET http://localhost:9000/picture/15 HTTP/1.1



#######################PROPIEDAD##################################
###
GET http://localhost:9000/properties HTTP/1.1
###
POST http://localhost:9000/properties HTTP/1.1
Content-Type: application/json

{
    "id_pais": 1,
    "id_ciudad": 1,
    "name": "Suite Empresarial",
    "price":200 ,
    "description":"Esta suite tiene un amplio closet, el piso es de tablones de madera chanul , amplias ventanas que la hacen muy luminosa y cálida y desde las cuales puedes tener una hermosa vista del paisaje.",
    "address":"Avenida Americas",
    "beds":"1",
    "toileds":"5",
    "square":"m2"
   
}

###
GET http://localhost:9000/properties/search/"100" HTTP/1.1
###
GET http://localhost:9000/properties/15 HTTP/1.1

###
DELETE http://localhost:9000/properties/2 HTTP/1.1

###
PUT http://localhost:9000/properties/10 HTTP/1.1
Content-Type: application/json

{
    "name": "Suite Ejemplo images",
    "price": 280,
    "description":"Esta suite tiene un amplio closet, el piso es de tablones de madera chanul , amplias ventanas que la hacen muy luminosa y cálida y desde las cuales puedes tener una hermosa vista del paisaje.",
    "address":"el condado S6-130 norte quito",
    "beds":"8",
    "toileds":"2",
    "square":"2m 4m 8m2"

}