

####################USERS##############
##
GET http://localhost:9000/users HTTP/1.1


###
POST http://localhost:9000/users/register HTTP/1.1
Content-Type: application/json

{
    "name":"jose",
    "lastName":"ostaiza",
    "email":"joseostaiza57@gmai.com",
    "userName":"jose",
    "password":"123456"

   
}

###
GET http://localhost:9000/users/10 HTTP/1.1


####################CIUDAD##############
##
GET http://localhost:9000/properties/ciudad HTTP/1.1



####################PICTURES############################
###
GET http://localhost:9000/picture HTTP/1.1

###
POST http://localhost:9000/picture HTTP/1.1
Content-Type: application/json

{
    "img_url": "http://mariusn.com/themes/reales/images/prop/1-1.png",
    "img_datetime" : "26-10-2021",
    "img_principal":"0",
    "img_enable":"1",
    "id_prop":18
   
}
###
GET http://localhost:9000/picture/15 HTTP/1.1
###
GET http://localhost:9000/picture/automovil/1 HTTP/1.1



#######################PROPIEDAD##################################
###
GET http://localhost:9000/properties HTTP/1.1
###
POST http://localhost:9000/properties HTTP/1.1
Content-Type: application/json

{
    "id_pais": 1,
    "id_ciudad": 1,
    "name": "Suite Empresarial",
    "price":200 ,
    "description":"Esta suite tiene un amplio closet, el piso es de tablones de madera chanul , amplias ventanas que la hacen muy luminosa y cálida y desde las cuales puedes tener una hermosa vista del paisaje.",
    "address":"Avenida Americas",
    "beds":"1",
    "toileds":"5",
    "square":"m2"
   
}

###
GET http://localhost:9000/properties/search/"sale" HTTP/1.1
###
GET http://localhost:9000/properties/15 HTTP/1.1

###
GET http://localhost:9000/properties/src/15 HTTP/1.1

###
DELETE http://localhost:9000/properties/2 HTTP/1.1

###
PUT http://localhost:9000/properties/16 HTTP/1.1
Content-Type: application/json

{
    "name": "Suite Ejemplo images",
    "price": 150,
    "description":"Esta suite tiene un amplio closet, el piso es de tablones de madera chanul , amplias ventanas que la hacen muy luminosa y cálida y desde las cuales puedes tener una hermosa vista del paisaje.",
    "address":"el condado S6-130 norte quito",
    "beds":"8",
    "toileds":"2",
    "square":"2m 4m 8m2"

}



#######################Automoviles##################################
###
GET http://localhost:9000/automoviles HTTP/1.1

###
POST http://localhost:9000/automoviles HTTP/1.1
Content-Type: application/json

{
    "id_pais": 1,
    "id_ciudad": 1,
    "id_marca":8,
    "modelo":"Q5",
    "precio":"69,900",
    "descripcion":"Auto en perfecto estado. A toda prueba",
    "estado":"nuevo",
    "anio":"2021",
    "km":"33,000 Km"
   
}

###
GET http://localhost:9000/automoviles/search/"Quito" HTTP/1.1
###
GET http://localhost:9000/automoviles/1 HTTP/1.1

###
GET http://localhost:9000/properties/src/15 HTTP/1.1
###
GET http://localhost:9000/properties/search/-/Estudio/ HTTP/1.1

###
DELETE http://localhost:9000/properties/2 HTTP/1.1

###
PUT http://localhost:9000/properties/16 HTTP/1.1



###################################################
#
GET http://localhost:9000/banner/findId/"1" HTTP/1.1








###
PUT http://localhost:9000/users/6 HTTP/1.1
Content-Type: application/json

{
    "name": "pauilana",
    "lastName": "",
    "userName":"",
    "password":"",
    "email": "",
    "phone": "0983499852",
    "address": "solanda",
    "city": "quito",
    "estate": "ecuador",
    "zipCode": "2454"
}

###
GET http://localhost:9000/users/img/avatar/'5' HTTP/1.1
